controllers_web:
    resource:
        path: ../src/Infrastructure/Http/Web/
        namespace: App\Infrastructure\Http\Web
    type: attribute

controllers_api:
    resource:
        path: ../src/Infrastructure/Http/Api/
        namespace: App\Infrastructure\Http\Api
    type: attribute
    prefix: /api
